import { doc, getDoc, getDocs, setDoc, updateDoc, writeBatch, collection, type DocumentData } from 'firebase/firestore'
import { auth, db } from '../lib/firebase'
import {
  sanitizeAbout,
  sanitizeHeroContent,
  sanitizeProjects,
  sanitizeServices,
  sanitizeSkills,
  stripUndefined,
} from '../lib/firestoreSanitize'
import type {
  AnalyticsData,
  ChatSummary,
  ContactSubmission,
  FirestoreAbout,
  FirestoreHeroContent,
  FirestoreProjectItem,
  FirestoreServiceItem,
  FirestoreSiteTheme,
  FirestoreSkillItem,
} from '../types/firestore'

const toDate = (value: unknown): Date | null => {
  if (!value) return null
  if (value instanceof Date) return value
  if (typeof value === 'object' && value !== null && 'toDate' in value) {
    return (value as { toDate: () => Date }).toDate()
  }
  return null
}

async function ensureFirestoreWriteAuth(): Promise<void> {
  const user = auth.currentUser
  if (!user) {
    throw new Error('You must be logged in to save. Please sign in again.')
  }
  await user.getIdToken(true)
}

export async function fetchHeroContent(): Promise<FirestoreHeroContent | null> {
  const snap = await getDoc(doc(db, 'heroContent', 'main'))
  return snap.exists() ? (snap.data() as FirestoreHeroContent) : null
}

export async function fetchAbout(): Promise<FirestoreAbout | null> {
  const snap = await getDoc(doc(db, 'about', 'main'))
  return snap.exists() ? (snap.data() as FirestoreAbout) : null
}

export async function fetchSkills(): Promise<FirestoreSkillItem[]> {
  const snap = await getDoc(doc(db, 'skills', 'main'))
  if (!snap.exists()) return []
  const items = (snap.data().items ?? []) as FirestoreSkillItem[]
  return [...items].sort((a, b) => a.order - b.order)
}

export async function fetchProjects(): Promise<FirestoreProjectItem[]> {
  const snap = await getDoc(doc(db, 'projects', 'main'))
  if (!snap.exists()) return []
  const items = (snap.data().items ?? []) as FirestoreProjectItem[]
  return [...items].sort((a, b) => a.order - b.order)
}

export async function fetchServices(): Promise<FirestoreServiceItem[]> {
  const snap = await getDoc(doc(db, 'services', 'main'))
  if (!snap.exists()) return []
  const items = (snap.data().items ?? []) as FirestoreServiceItem[]
  return [...items].sort((a, b) => a.order - b.order)
}

export async function fetchSiteTheme(): Promise<FirestoreSiteTheme | null> {
  const snap = await getDoc(doc(db, 'siteTheme', 'main'))
  return snap.exists() ? (snap.data() as FirestoreSiteTheme) : null
}

export async function fetchContactSubmissions(): Promise<ContactSubmission[]> {
  try {
    const snap = await getDocs(collection(db, 'contactSubmissions'))
    return snap.docs
      .map((d) => {
        const data = d.data() as DocumentData
        return {
          id: d.id,
          name: data.name,
          email: data.email,
          message: data.message,
          read: data.read ?? false,
          timestamp: toDate(data.timestamp),
        }
      })
      .sort((a, b) => (b.timestamp?.getTime() ?? 0) - (a.timestamp?.getTime() ?? 0))
  } catch (error) {
    console.error('fetchContactSubmissions failed:', error)
    return []
  }
}

export async function fetchChatSummaries(): Promise<ChatSummary[]> {
  try {
    const snap = await getDocs(collection(db, 'chatSummaries'))
    return snap.docs
      .map((d) => {
        const data = d.data() as DocumentData
        return {
          id: d.id,
          autoGeneratedTitle: data.autoGeneratedTitle,
          summaryText: data.summaryText,
          fullTranscript: data.fullTranscript ?? [],
          visitorInfo: data.visitorInfo ?? null,
          timestamp: toDate(data.timestamp),
        }
      })
      .sort((a, b) => (b.timestamp?.getTime() ?? 0) - (a.timestamp?.getTime() ?? 0))
  } catch (error) {
    console.error('fetchChatSummaries failed:', error)
    return []
  }
}

export async function fetchAnalytics(): Promise<AnalyticsData> {
  const snap = await getDoc(doc(db, 'analytics', 'main'))
  if (!snap.exists()) return { visitorCount: 0, lastUpdated: null }
  const data = snap.data()
  return {
    visitorCount: data.visitorCount ?? 0,
    lastUpdated: toDate(data.lastUpdated),
  }
}

export async function saveHeroContent(data: FirestoreHeroContent) {
  await ensureFirestoreWriteAuth()
  const payload = sanitizeHeroContent(data)
  await setDoc(doc(db, 'heroContent', 'main'), payload, { merge: true })
}

export async function saveAbout(data: FirestoreAbout) {
  await ensureFirestoreWriteAuth()
  const payload = sanitizeAbout(data)
  await setDoc(doc(db, 'about', 'main'), payload, { merge: true })
}

export async function saveSkills(items: FirestoreSkillItem[]) {
  await ensureFirestoreWriteAuth()
  const payload = sanitizeSkills(items)
  await setDoc(doc(db, 'skills', 'main'), { items: payload })
}

export async function saveProjects(items: FirestoreProjectItem[]) {
  await ensureFirestoreWriteAuth()
  const payload = sanitizeProjects(items)
  await setDoc(doc(db, 'projects', 'main'), { items: payload })
}

export async function saveServices(items: FirestoreServiceItem[]) {
  await ensureFirestoreWriteAuth()
  const payload = sanitizeServices(items)
  await setDoc(doc(db, 'services', 'main'), { items: payload })
}

export async function saveSiteTheme(data: FirestoreSiteTheme) {
  await ensureFirestoreWriteAuth()
  await setDoc(doc(db, 'siteTheme', 'main'), stripUndefined(data), { merge: true })
}

export async function markContactAsRead(id: string, read: boolean) {
  await updateDoc(doc(db, 'contactSubmissions', id), { read })
}

export async function uploadFile(path: string, file: File): Promise<string> {
  const { uploadFileWithProgress } = await import('./storageUpload')
  return uploadFileWithProgress(path, file, () => {})
}

export { uploadFileWithProgress, safeStorageFileName } from './storageUpload'

export async function seedDefaultContent(seedData: {
  hero: FirestoreHeroContent
  about: FirestoreAbout
  skills: FirestoreSkillItem[]
  projects: FirestoreProjectItem[]
  services: FirestoreServiceItem[]
  theme: FirestoreSiteTheme
}) {
  const batch = writeBatch(db)
  batch.set(doc(db, 'heroContent', 'main'), seedData.hero)
  batch.set(doc(db, 'about', 'main'), seedData.about)
  batch.set(doc(db, 'skills', 'main'), { items: seedData.skills })
  batch.set(doc(db, 'projects', 'main'), { items: seedData.projects })
  batch.set(doc(db, 'services', 'main'), { items: seedData.services })
  batch.set(doc(db, 'siteTheme', 'main'), seedData.theme)
  await batch.commit()
}
