export interface FirestoreHeroContent {
  name: string
  tagline: string
  summary: string
  intro?: string
  profileImageUrl?: string
  resumeUrl: string
}

export interface FirestoreAbout {
  bio: string
  highlights: Array<{ label: string }>
}

export interface FirestoreSkillItem {
  id: string
  category: string
  name: string
  percentage: number
  order: number
}

export interface FirestoreProjectItem {
  id: string
  title: string
  description: string
  techStack: string[]
  githubUrl?: string
  liveUrl?: string
  imageUrl?: string
  featured: boolean
  order: number
  comingSoon?: boolean
}

export interface FirestoreServiceItem {
  id: string
  title: string
  description: string
  category: string
  iconName?: string
  badge?: string
  order: number
}

export interface FirestoreSiteTheme {
  primary: string
  secondary: string
  accent: string
  bg: string
  surface: string
  text: string
}

export interface ContactSubmission {
  id: string
  name: string
  email: string
  message: string
  read: boolean
  timestamp: Date | null
}

export interface ChatSummary {
  id: string
  autoGeneratedTitle: string
  summaryText: string
  fullTranscript: Array<{ role: string; content: string }>
  visitorInfo?: { name?: string; email?: string } | null
  timestamp: Date | null
}

export interface AnalyticsData {
  visitorCount: number
  lastUpdated: Date | null
}

export interface ChatMessage {
  role: 'user' | 'assistant'
  content: string
}
