import { callGroq } from './_lib/groq.js'
import { sendAdminEmail } from './_lib/email.js'
import { getFirestore } from './_lib/firebaseAdmin.js'
import { handleOptions, readJsonBody, setCors } from './_lib/handler.js'
import { checkRateLimit, getClientIp } from './_lib/rateLimit.js'

export default async function handler(req, res) {
  setCors(res)
  if (handleOptions(req, res)) return

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  try {
    const ip = getClientIp(req)
    if (!checkRateLimit(ip)) {
      return res.status(429).json({ error: 'Too many requests.' })
    }

    const body = await readJsonBody(req)
    const { transcript, visitorInfo } = body

    if (!Array.isArray(transcript) || transcript.length === 0) {
      return res.status(400).json({ error: 'Transcript is required.' })
    }

    const conversationText = transcript
      .map((m) => `${m.role}: ${m.content}`)
      .join('\n')

    const summaryPrompt = `Analyze this portfolio chatbot conversation and respond in JSON only with this exact shape:
{"title":"short descriptive title","summary":"concise 2-4 sentence summary"}

Conversation:
${conversationText}`

    const rawSummary = await callGroq([{ role: 'user', content: summaryPrompt }], 0.3)

    let autoGeneratedTitle = 'Portfolio Chat Inquiry'
    let summaryText = rawSummary

    try {
      const jsonMatch = rawSummary.match(/\{[\s\S]*\}/)
      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0])
        autoGeneratedTitle = parsed.title ?? autoGeneratedTitle
        summaryText = parsed.summary ?? summaryText
      }
    } catch {
      summaryText = rawSummary
    }

    const { db, admin } = getFirestore()
    const docRef = await db.collection('chatSummaries').add({
      autoGeneratedTitle,
      summaryText,
      fullTranscript: transcript,
      visitorInfo: visitorInfo ?? null,
      timestamp: admin.firestore.FieldValue.serverTimestamp(),
    })

    const visitorLine = visitorInfo
      ? `<p><strong>Visitor:</strong> ${visitorInfo.name ?? 'Unknown'} (${visitorInfo.email ?? 'no email'})</p>`
      : ''

    await sendAdminEmail(
      `Chat Summary: ${autoGeneratedTitle}`,
      `
        <h2>Chatbot Conversation Summary</h2>
        <p><strong>Title:</strong> ${autoGeneratedTitle}</p>
        ${visitorLine}
        <p><strong>Summary:</strong></p>
        <p>${summaryText}</p>
        <p><em>View full transcript in the admin panel.</em></p>
      `,
    )

    return res.status(200).json({
      success: true,
      id: docRef.id,
      title: autoGeneratedTitle,
      summary: summaryText,
    })
  } catch (error) {
    console.error('summarizeChat error:', error)
    const message = error instanceof Error ? error.message : 'Internal server error'
    return res.status(500).json({ error: message })
  }
}
